// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBHzzyhy4Zg5FmExfURD80lWMFaAG0Vo',
    appId: '1:460125697342:web:302952d72a6743a560a86f',
    messagingSenderId: '460125697342',
    projectId: 'foodpanda-clone-320be',
    authDomain: 'foodpanda-clone-320be.firebaseapp.com',
    databaseURL: 'https://foodpanda-clone-320be-default-rtdb.firebaseio.com',
    storageBucket: 'foodpanda-clone-320be.appspot.com',
    measurementId: 'G-4BJ9RJ1RSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA1Ru0V6GCKRwNjzHnppc4uRyQcuo-z-8',
    appId: '1:460125697342:android:845d17a539f28a3460a86f',
    messagingSenderId: '460125697342',
    projectId: 'foodpanda-clone-320be',
    databaseURL: 'https://foodpanda-clone-320be-default-rtdb.firebaseio.com',
    storageBucket: 'foodpanda-clone-320be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQKc79T0fidK3mZrWhN9ZStEnhJDc-rI',
    appId: '1:460125697342:ios:48a39aa06a948e4860a86f',
    messagingSenderId: '460125697342',
    projectId: 'foodpanda-clone-320be',
    databaseURL: 'https://foodpanda-clone-320be-default-rtdb.firebaseio.com',
    storageBucket: 'foodpanda-clone-320be.appspot.com',
    iosBundleId: 'com.nofliegroup.usersNoflieFoodpandaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQKc79T0fidK3mZrWhN9ZStEnhJDc-rI',
    appId: '1:460125697342:ios:48a39aa06a948e4860a86f',
    messagingSenderId: '460125697342',
    projectId: 'foodpanda-clone-320be',
    databaseURL: 'https://foodpanda-clone-320be-default-rtdb.firebaseio.com',
    storageBucket: 'foodpanda-clone-320be.appspot.com',
    iosBundleId: 'com.nofliegroup.usersNoflieFoodpandaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCBHzzyhy4Zg5FmExfURD80lWMFaAG0Vo',
    appId: '1:460125697342:web:3b97d9c7c35a200960a86f',
    messagingSenderId: '460125697342',
    projectId: 'foodpanda-clone-320be',
    authDomain: 'foodpanda-clone-320be.firebaseapp.com',
    databaseURL: 'https://foodpanda-clone-320be-default-rtdb.firebaseio.com',
    storageBucket: 'foodpanda-clone-320be.appspot.com',
    measurementId: 'G-TN98L4KYYZ',
  );
}
